spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/olx-users
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dev
    password: root
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect